# Generated by Django 5.1.3 on 2025-01-01 23:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='status',
            field=models.CharField(choices=[('blocked', 'Blocked'), ('unblocked', 'Unblocked')], default='blocked', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('blocker', 'blocked_user')},
        ),
    ]
