# Generated by Django 5.1.3 on 2024-12-21 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_gameinvite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameInvite',
        ),
    ]
